/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Model.CrearXML;
import Utils.Tractar;
import java.io.File;
import java.util.Set;
import java.util.TreeSet;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Dolo
 */
public class MenuInici extends javax.swing.JFrame {

    /**
     * Creates new form Ejemplo
     */
    private Tractar tr;

    public MenuInici() {
        initComponents();
        tr = new Tractar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txFitxer = new javax.swing.JTextField();
        JSmateries = new javax.swing.JScrollPane();
        jtMateries = new javax.swing.JList();
        botoExaminar = new javax.swing.JLabel();
        botoSortir = new javax.swing.JLabel();
        botoGenerar = new javax.swing.JLabel();
        fons = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txFitxer.setBackground(new java.awt.Color(255, 255, 255));
        txFitxer.setEditable(false);
        txFitxer.setFont(new java.awt.Font("Buxton Sketch", 0, 18)); // NOI18N
        txFitxer.setForeground(new java.awt.Color(255, 255, 255));
        txFitxer.setBorder(null);
        txFitxer.setCaretColor(new java.awt.Color(255, 255, 255));
        txFitxer.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        txFitxer.setOpaque(false);
        txFitxer.setRequestFocusEnabled(false);
        txFitxer.setSelectionColor(new java.awt.Color(255, 255, 255));
        txFitxer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFitxerActionPerformed(evt);
            }
        });
        getContentPane().add(txFitxer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 310, 40));

        jtMateries.setFont(new java.awt.Font("Buxton Sketch", 0, 18)); // NOI18N
        jtMateries.setForeground(new java.awt.Color(0, 153, 153));
        JSmateries.setViewportView(jtMateries);

        getContentPane().add(JSmateries, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 190, 300, 140));

        botoExaminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/botoExaminar_1.PNG"))); // NOI18N
        botoExaminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botoExaminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botoExaminarMouseClicked(evt);
            }
        });
        botoExaminar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                botoExaminarMouseDragged(evt);
            }
        });
        getContentPane().add(botoExaminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        botoSortir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/botoSortir.PNG"))); // NOI18N
        botoSortir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botoSortir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botoSortirMouseClicked(evt);
            }
        });
        getContentPane().add(botoSortir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, -1, -1));

        botoGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/botoGenerar.PNG"))); // NOI18N
        botoGenerar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botoGenerar.setEnabled(false);
        botoGenerar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botoGenerarMouseClicked(evt);
            }
        });
        getContentPane().add(botoGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        fons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/Captura.PNG"))); // NOI18N
        fons.setText("Selecciona les matèries de les quals vols generar llistes:");
        getContentPane().add(fons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 390));

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void txFitxerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFitxerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFitxerActionPerformed

    private void botoExaminarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoExaminarMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_botoExaminarMouseDragged

    private void botoExaminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoExaminarMouseClicked
        //Creació un nou filtre
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Comma-Separated Values(*.csv)", "csv");
        //Creació  fileChooser
        JFileChooser obrirFitxer = new JFileChooser();
        //Afegir el filtre
        obrirFitxer.setFileFilter(filter);
        //Indiquem el titol de la finestra
        obrirFitxer.setDialogTitle("Generador de llistats");
        //Creacio estructura que conte totes les matèries 
        Set<String> treeMateries = new TreeSet<String>();
        //Resultat de l'acció de l'usuari
        int result = obrirFitxer.showOpenDialog(null);
        //Comprovar la acció realitzada
        if (result == JFileChooser.APPROVE_OPTION) {
            //Creació fitxer seleccionat
            File file = obrirFitxer.getSelectedFile();
            //Visualització nom fitxer
            txFitxer.setText(file.getName());
            txFitxer.setEditable(false);
            txFitxer.setEnabled(false);
            //Activació botó Generació llistes
            botoGenerar.setEnabled(true);
          
            //Crida al mètode de creació de alumnes i retorna una array amb el total d'asignatures
            treeMateries = tr.asignatures(file.getAbsolutePath());


            //Visualització valors l'estructura Jlist requereix un ListModel per ser omplenada
            DefaultListModel defaultlistModel = new DefaultListModel();
            for (String aux : treeMateries) {
                defaultlistModel.addElement(aux);
            }

            jtMateries.setModel(defaultlistModel);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_botoExaminarMouseClicked

    private void botoSortirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoSortirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_botoSortirMouseClicked

    private void botoGenerarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoGenerarMouseClicked
        // TODO add your handling code here:
        TreeSet<String> materiesSeleccio = new TreeSet<String>(jtMateries.getSelectedValuesList());
        CrearXML crear = new CrearXML();

        crear.crearLlistaMateria(materiesSeleccio, tr.getTreeAlumne());

        FileNameExtensionFilter filter = new FileNameExtensionFilter("eXtensible Markup Language(*.xml)", "xml");
        //Creació  fileChooser
        JFileChooser desarFitxer = new JFileChooser();
        //Afegir el filtre
        desarFitxer.setFileFilter(filter);
        //Indiquem el titol de la finestra
//        fileChooser.setDialogTitle("Generador de llistats");
        int result = desarFitxer.showSaveDialog(null);
        try {
            if (result == JFileChooser.APPROVE_OPTION) {
                File file = desarFitxer.getSelectedFile();
                String path = file.getAbsolutePath();
                crear.desarFitxer(path);

                if (!(path.endsWith(".xml"))) {
                    File temp = new File(path + ".xml");
                    //Rename Fitxer
                    file.renameTo(temp);
                }
                JOptionPane.showMessageDialog(null, "Fitxer desat correctament", null, JOptionPane.INFORMATION_MESSAGE);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al deixar fitxer", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botoGenerarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new MenuInici().setVisible(true);
            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JSmateries;
    private javax.swing.JLabel botoExaminar;
    private javax.swing.JLabel botoGenerar;
    private javax.swing.JLabel botoSortir;
    private javax.swing.JLabel fons;
    private javax.swing.JList jtMateries;
    private javax.swing.JTextField txFitxer;
    // End of variables declaration//GEN-END:variables
}
